---
name: postgres

instance_groups:
- azs:
  - z1
  name: postgres
  networks:
  - name: default
  persistent_disk_type: default
  stemcell: default
  vm_type: default
  instances: 2
  jobs:
  - name: vip
    properties:
      vip: (( vip_ip ))
    release: postgres
  - name: postgres
    properties:
      postgres:
        config:
          max_connections: 500
        databases:
        - extensions:
          - citext
          name: diegodb
          users:
          - hank
        - extensions:
          - citext
          name: uaadb
          users:
          - hank
        - extensions:
          - citext
          name: ccdb
          users:
          - hank
        hba:
        - host all all 0.0.0.0/0 md5
        - host all all ::/0 md5
        replication:
          enabled: true
        users:
        - admin: true
          password: propane
          username: hank
    release: postgres


- azs:
  - z1
  name: smoke-tests
  instances: 1
  lifecycle: errand
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: smoke-tests
    properties:
      postgres:
        smoke-tests:
          backend:
            port: 6432
          target:
            port: 5432
            username: hank
            password: propane
    release: postgres


releases:
- name: postgres
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-120000

releases:
- name: postgres
  version: 3.0.0
  url: https://github.com/cloudfoundry-community/postgres-boshrelease/releases/download/v3.0.0/postgres-3.0.0.tgz
  sha1: a5070c285d44b3ac0fb678b1ae640461668b87c5
