---
instance_groups:
- azs:
  - z1
  instances: 2
  jobs:
  - name: haproxy
    properties:
      ha_proxy:
        tcp:
        - backend_port: 5432
          backend_servers:
          - 10.200.200.131
          - 10.200.200.132
          name: postgres
          port: 5432
    release: haproxy
  - name: keepalived
    properties:
      keepalived:
        healthcheck_name: whoguardstheguards
        vip: 10.200.200.254
    release: haproxy
  name: haproxy
  networks:
  - name: blacksmith
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 2
  jobs:
  - name: postgres
    properties:
      pgpool:
        databases:
        - extensions:
          - citext
          name: diegodb
          users:
          - cloudfoundry
        - extensions:
          - citext
          name: uaadb
          users:
          - cloudfoundry
        - extensions:
          - citext
          name: ccdb
          users:
          - cloudfoundry
        users: &users
        - admin: true
          password: test
          username: cloudfoundry
      postgres:
        config:
          port: 6432
        hba:
        - host all all 0.0.0.0/0 md5
        - host all all ::/0 md5
        replication:
          enabled: true
    release: postgres
  - name: pgpool
    properties:
      pgpool:
        ssh_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEAw8yNyfVI/h8hYPQtuq/gpB3rXUoL5gzQAZPk+5SFDSSFtyEc
          HNMMDcH8Jb+b2EqKRWTDfjVvum/pZn6/exOl+eQYHXB7p33ldRfs/I2dFbw92Eu8
          vrGRPDPQEk3dckD2flxqe6C1bLv78HdgQIrzUYar6S/EwUhJS3xmJNRl5kwvx4Ci
          BBGvtzpHObFIvstYqMIxpws0o0atrThJZMBnLZqcL2+5sAYq/PgVMMIKgXa0v89N
          aKJuVF2uk6Y1TWNgW4YQ4zVTkAz/Z4rYBRI2Kzs5WynIfdBB5BlcKkL4D6KET7IW
          MmEuNEyOqrBjKrgd0EX2/2WrJb/u/4isyre8sQIDAQABAoIBABOG6v0hQU5WvHV2
          5Lihob28XiTHpbgjvvrpTQTqIvrUkaFZ4/vb8G/O0N7S5TAE/xU8n2KO4b2uO5DF
          Q0N7CiqJ3P3SogJqQ+ARqsjlNq1cQK65nvFFtD5UzIOG0Hb8k5i2jsgVlwJpHQ82
          WJsXQHz4+VwgL3c3RlgI6Ab0R9VXxyHociwtyRFxz/TLOK1YRuAHnwb9vEEV7Fl2
          BxxiNXkJSQ6zr4FmN9znDygAOYYZZaurNoqHLZbqoQd1TVVgezTVpf24rM/fsqS8
          uuv4yEqkp8VoSFnkwMaqslXATw/mXYt/atpetregMxNIzHsUG2gwTx4JFEVeMzTJ
          ENkHO4ECgYEA5Cjv2h7C6C4jKgH0qzvOgG6LocKT9QkasNwiCSr6Iz73/icya2tt
          KHXZsGM5an1kVBt39waP0hFYR9ZABUwfFm670KrqPZN/PoendY9dJl44sYQKc5R3
          RoK/noz3WCQe8mnCZBtqO572fvrWWo/WmM0xiDC2JjKBYqOITVOrXQ0CgYEA27DB
          gJYIsuKX17XjkZUfxgqk5Sz5eK0zS31U5ZNWpKCpbccxJ9dUpujsadpnqhvFdhBo
          zEm4rUHCWS81HlpXYTelKnej+cOpis5dmeTMZTV44Q/VyMM7vJP50aaXlAE8Omcm
          6IqGuo9s1FQ0SQBhbBb89ZvqpondY9JG96q/HTUCgYBbk/bZxNkUmlgw50IObN3w
          /O38yn3ar4HQFTtwFJj8Bq1BjPgW17Kjt9Hdk6YbESNxAul+9FpLxfx6MQvXVHtx
          5JZsJf4JIyfCsG5NqHKKEO2OiuIrDB9n5NkGyawJ682kHUESL1LPhXmI9COPjAZl
          pI7KDEtAP6thLSRrbTbuDQKBgQDGgF9XIDmb6MHqVp7Y3DVpbBSyPoDrWRQQEZ60
          EP0oo0Jzvpfbt+T1K2DyBDXGrnEszIbkj3gelFxW2SDV3Cs33F+Qj6nJ89EtammI
          tAM7L6WZNgWk8UL4kXwYwr4TLUqOOsYdN42k5BMhhzP3AjEEyYCnK8pJ0CgKGeWl
          wtIMQQKBgCLQMiMcIu4CGO3c0GpSGXgGDfwev5M5lbwjJAIm8YnQ7NywgTLh2EC7
          7iQ9oqxt9vITgNcK2Ovr4//gtHzs5mdRvZ9lMtJ0xGfuHJDI9NpxbmPv04lsR/pj
          ry/fDqYhLP36MPm4OW9C3zFDZPxxthAIDUIdRzWr5/iG1I+Dur+X
          -----END RSA PRIVATE KEY-----
        users: *users
      pcp:
        system_password: secret
        backend:
          port: 6432
        config:
          enable_pool_hba: false
          port: 5432
        debug: true
    release: postgres
  name: postgres
  networks:
  - name: blacksmith
  persistent_disk_type: default
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: smoke-tests
    properties:
      postgres:
        smoke-tests:
          backend:
            port: 6432
          target:
            password: test
            port: 5432
            username: user
    release: postgres
  lifecycle: errand
  name: smoke-tests
  networks:
  - name: blacksmith
  stemcell: default
  vm_type: default
name: postgres
releases:
- name: postgres
  version: latest
- name: haproxy
  sha1: 7898c1894c4b3254aa4a0ade0a02d33cf6c5c59a
  url: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/download/v8.7.0/haproxy-8.7.0.tgz
  version: 8.7.0
stemcells:
- alias: default
  os: ubuntu-trusty
  version: '3468.47'
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000
