---
name: postgres

instance_groups:
- azs:
  - z1
  name: postgres
  networks:
  - name: default
  persistent_disk_type: default
  stemcell: default
  vm_type: default
  instances: 1
  jobs:
  - name: postgres
    properties:
      postgres:
        config:
          max_connections: 500
        databases:
        - extensions:
          - citext
          name: diegodb
          users:
          - hank
        - extensions:
          - citext
          name: uaadb
          users:
          - hank
        - extensions:
          - citext
          name: ccdb
          users:
          - hank
        hba:
        - host all all 0.0.0.0/0 md5
        - host all all ::/0 md5
        users:
        - admin: true
          password: propane
          username: hank
    release: postgres


- azs:
  - z1
  name: smoke-tests
  instances: 1
  lifecycle: errand
  networks:
  - name: default
  stemcell: default
  vm_type: default
  jobs:
  - name: smoke-tests
    properties:
      postgres:
        smoke-tests:
          backend:
            port: 6432
          target:
            port: 5432
            username: hank
            password: propane
    release: postgres

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-120000

releases:
- name: postgres
  version: 3.1.4
  url: https://github.com/cloudfoundry-community/postgres-boshrelease/releases/download/v3.1.4/postgres-3.1.4.tgz
  sha1: 3c5b80b6c09d191783634be269896c86fc8e3d7c
