---
name: postgres

instance_groups:
  - name: postgres
    azs: [z1]
    networks: [{name: default }]
    persistent_disk: 2048
    stemcell: default
    vm_type: default
    instances: 1
    jobs:
      - name: postgres
        release: postgres
        properties:
          postgres:
            config:
              max_connections: 500
            databases:
              - name:       diegodb
                extensions: [citext]
                users:      [hank]

              - name:       uaadb
                extensions: [citext]
                users:      [hank]

              - name:       ccdb
                extensions: [citext]
                users:      [hank]

            hba:
              - host all all 0.0.0.0/0 md5
              - host all all ::/0 md5

            users:
              - username: hank
                password: propane
                admin: true

  - name: smoke-tests
    instances: 1
    azs: [z1]
    lifecycle: errand
    networks: [{name: default}]
    stemcell: default
    vm_type: default
    jobs:
      - name: smoke-tests
        release: postgres
        properties:
          postgres:
            smoke-tests:
              backend:
                port: 6432
              target:
                port: 5432
                username: hank
                password: propane

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-120000

releases:
- name:    postgres
  version: 3.2.0
  url:     https://github.com/cloudfoundry-community/postgres-boshrelease/releases/download/v3.2.0/postgres-3.2.0.tgz
  sha1:    470c2b6d98d988ad9dc36dedcd8133e247de63f7
