meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: postgres
    templates:
    - { release: postgres, name: postgres }
    - { release: postgres, name: pgpool }
    instances: 3
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set postgres networks" ))

    properties:
      postgres:
        config:
          port: 6432
        replication:
          enabled: true
        hba:
          - host all all 0.0.0.0/0 md5
          - host all all ::/0 md5
      pgpool:
        debug: true
        databases:
          - name: animals
            users:
              - porcupine
              - hedgehog
        users:
          - username: porcupine
            password: quill
          - username: hedgehog
            password: frank
          - username: smoke-tests
            password: if-ya-got-em
        backend:
          port: 6432
        config:
          port: 5432
          enable_pool_hba: on
        hba: (( grab jobs.postgres.properties.postgres.hba ))
      pcp:
        system_password: secret

  - name: smoke-tests
    lifecycle: errand
    templates:
      - { release: postgres, name: smoke-tests }
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set smoke-tests networks" ))

    properties:
      postgres:
        smoke-tests:
          target:
            port:     5432
            username: smoke-tests
            password: if-ya-got-em
          backend:
            port:     6432



networks: (( param "please set networks" ))

properties: {}
