---
meta:
  name:    postgres
  target:  sw
  url:     https://ci.starkandwayne.com
  # test-errands: smoke-tests

  initial_version: 1.0.0

  bosh-lite:
    target: https://10.58.111.44:25555
    username: (( vault "secret/bosh-lites/lite44/users/admin:username" ))
    password: (( vault "secret/bosh-lites/lite44/users/admin:password" ))
    cacert:   (( vault "secret/bosh-lites/lite44/certs:rootCA.pem" ))

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   postgres-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/shared/github:private" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook:  (( vault "secret/pipelines/postgres-boshrelease/slack:webhook" ))
    channel:  '#postgres-boshrelease'
    username: starkandwayne-ci
    icon:     https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
