---
meta:
  name:    postgres
  target:  pipes
  url:     https://pipes.starkandwayne.com
  # test-errands: smoke-tests

  initial_version: 1.0.0

  bosh-lite:
    target: https://10.200.131.9:25555
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  cloudfoundry-community
    repo:   postgres-boshrelease
    branch: master
    private_key:  ((github.private-key))
    access_token: ((github.access-token))

  slack:
    webhook: ((slack.webhook))
    channel:  '#postgres-boshrelease'
    username: starkandwayne-ci
    icon:     https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
